### ISSUE TITLE
npm test error and feathers-chat not working

### ISSUE THREAD

**Issue by hedikasmanto** [feathersjs/feathers-chat#2] opened 2016-03-18 04:16 UTC
~/D/feathers-chat-master npm test                                    11:04:17

> feathers-chat@0.1.0 test /Users/forte/Downloads/feathers-chat-master
> npm run jshint && npm run mocha

> feathers-chat@0.1.0 jshint /Users/forte/Downloads/feathers-chat-master
> jshint src/. test/. --config

> feathers-chat@0.1.0 mocha /Users/forte/Downloads/feathers-chat-master
> mocha test/ --recursive

module.js:327
    throw err;
    ^

Error: Cannot find module '../../../../src/services/message/hooks/verify.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/forte/Downloads/feathers-chat-master/test/services/message/hooks/verify.test.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/forte/Downloads/feathers-chat-master/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/forte/Downloads/feathers-chat-master/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/forte/Downloads/feathers-chat-master/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/forte/Downloads/feathers-chat-master/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/forte/.nvm/versions/node/v4.4.0/bin/node" "/Users/forte/.nvm/versions/node/v4.4.0/bin/npm" "run" "mocha"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! feathers-chat@0.1.0 mocha: `mocha test/ --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-chat@0.1.0 mocha script 'mocha test/ --recursive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the feathers-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha test/ --recursive
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs feathers-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls feathers-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/forte/Downloads/feathers-chat-master/npm-debug.log
npm ERR! Test failed.  See above for more details.

And while I run the chat app with "npm start", I can login to the chat-app but 0 users display

**Comment by ekryski** [comment] 2016-03-18 05:06
@hedikasmanto the failed test is a test that we forgot to rename.

I'm not sure. You said you were able to login so I assume you created a user but I can't reproduce that.

**Comment by ekryski** [comment] 2016-03-18 05:19
I pushed up a fix for the tests. They all pass now so I'm going to close this. If you still have problems with the demo app and you haven't modified it then feel free to open a new issue.

**Closed by ekryski** 2016-03-18 05:19 UTC

**Comment by hedikasmanto** [comment] 2016-03-18 06:10
Thanks @ekryski for your quick response. I think this problem only occurs on Safari browser and while I try it on Chrome browser, that demo app display users correctly, but still send message as Anonymous. 
![testing](https://cloud.githubusercontent.com/assets/9128724/13869771/b48fda34-ed0a-11e5-8265-127be0c0beef.jpg)

**Comment by ekryski** [comment] 2016-03-19 03:23
@hedikasmanto I've created a separate issue for that it failing on Safari #4. The Anonymous users are fixed now.
